import Header from './components/Header/Header'
import './styles/globals.scss'

export const metadata = {
  title: 'Next.js 13.2 MLB App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='layout'>
      <main>
        <Header />
        {children}
        </main>
      </body>
    </html>
  )
}
